language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 random.c -o random
  - ./random
  - gcov random.c || cat random.c 

after_success:
  - bash <(curl -s https://codecov.io/bash)
