# ~/.circleci/config.yml
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: uname -a && pwd && ls -lhtr /home/ && gcc -v && gcc -g3 /home/random.c -o random && cd ./home; ./random
