jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout # check out the code in the project directory
      - run: uname -a && pwd && ls && gcc -v && gcc -g3 random.c -o random && ./random
version: 2.1
workflows:
  main:
    jobs:
      - build
