version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~
    steps:
      - checkout
      - run:
          command:
            gcc -g3 /home/random.c -o random
            ./random
