# ~/.circleci/config.yml
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - run: uname -a && pwd && ls && gcc -v && gcc -g3 random.c -o random && ./random
