name: C
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: random
      run:  sudo apt-get install -y gcovr && gcc -ftest-coverage -g3 random.c -o random && ./random && gcov random.c
    - name: ciclo
      run:  gcc -ftest-coverage -g3 ciclo.c -o ciclo && ./ciclo && gcov ciclo.c
    - name: comparar
      run:  gcc -ftest-coverage -g3 comparar.c -o comparar && ./comparar && gcov comparar.c
