name: C
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: random
      run:  sudo apt-get install -y gcovr && gcc -ftest-coverage -g3 random.c -o random && ./random && gcov random.c
    - name: ciclo
      run:  gcc -ftest-coverage -g3 ciclo.c -o ciclo && ./ciclo && gcov ciclo.c
    - name: comparar
      run:  sudo apt-get install -y expect && gcc -ftest-coverage -g3 comparar.c -o comparar && chmod +x comparar.sh && ./comparar.sh && gcov comparar.c
    - name: matematica
      run:  gcc -ftest-coverage -g3 matematica.c -o matematica && chmod +x matematica.sh && ./matematica.sh && gcov matematica.c
