name: C
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: random
      run:  sudo apt-get install -y gcovr && gcc -ftest-coverage -g3 random.c -o random && ./random && gcov random.c
    - name: ciclo
      run:  gcc -ftest-coverage -g3 ciclo.c -o ciclo && ./ciclo && gcov ciclo.c
    - name: comparar
      run:  sudo apt-get install -y expect && gcc -ftest-coverage -g3 comparar.c -o comparar && chmod +x comparar.sh && ./comparar.sh && gcov comparar.c
    - name: matematica
      run:  gcc -ftest-coverage -g3 matematica.c -o matematica && chmod +x matematica.sh && ./matematica.sh && gcov matematica.c
    - name: inferencia
      run:  cat inferencia.c && gcc -ftest-coverage -g3 inferencia.c -o inferencia && ./inferencia && gcov inferencia.c
    - name: verificar
      run:  gcc -ftest-coverage -g3 verificar.c -o verificar && ./verificar && gcov verificar.c
    - name: petalas
      run:  gcc -ftest-coverage -g3 petalas.c -o petalas && chmod +x petalas.sh && ./petalas.sh && gcov petalas.c
    - name: espera
      run:  gcc -ftest-coverage -g3 espera.c -o espera && chmod +x espera.sh && ./espera.sh && gcov espera.c
    - name: decisao
      run:  gcc -ftest-coverage -g3 decisao.c -o decisao && chmod +x decisao.sh && ./decisao.sh && gcov decisao.c
    - name: floresta
      run:  gcc -ftest-coverage -g3 floresta.c -o floresta && chmod +x floresta.sh && ./floresta.sh && gcov floresta.c
    - name: enquanto
      run:  gcc -ftest-coverage -g3 enquanto.c -o enquanto && ./enquanto && gcov enquanto.c
    - name: para
      run:  gcc -ftest-coverage -g3 para.c -o para && ./para && gcov para.c
