name: C
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verficação de versão
      run:  lsb_release -a && gcc -v && bash -version
    - name: random
      run:  sudo apt-get install -y gcovr && gcc -ftest-coverage -g3 random.c -o random && ./random && gcov random.c
    - name: ciclo
      run:  gcc -ftest-coverage -g3 ciclo.c -o ciclo && ./ciclo && gcov ciclo.c
    - name: comparar
      run:  sudo apt-get install -y expect && gcc -ftest-coverage -g3 comparar.c -o comparar && chmod +x comparar.sh && ./comparar.sh && gcov comparar.c
    - name: matematica
      run:  gcc -ftest-coverage -g3 matematica.c -o matematica && chmod +x matematica.sh && ./matematica.sh && gcov matematica.c
    - name: inferencia
      run:  cat inferencia.c && gcc -ftest-coverage -g3 inferencia.c -o inferencia && ./inferencia && gcov inferencia.c
    - name: verificar
      run:  gcc -ftest-coverage -g3 verificar.c -o verificar && ./verificar && gcov verificar.c
    - name: petalas
      run:  gcc -ftest-coverage -g3 petalas.c -o petalas && chmod +x petalas.sh && ./petalas.sh && gcov petalas.c
    - name: espera
      run:  gcc -ftest-coverage -g3 espera.c -o espera && chmod +x espera.sh && ./espera.sh && gcov espera.c
    - name: decisao
      run:  gcc -ftest-coverage -g3 decisao.c -o decisao && chmod +x decisao.sh && ./decisao.sh && gcov decisao.c
    - name: floresta
      run:  gcc -ftest-coverage -g3 floresta.c -o floresta && chmod +x floresta.sh && ./floresta.sh && gcov floresta.c
    - name: enquanto
      run:  gcc -ftest-coverage -g3 enquanto.c -o enquanto && ./enquanto && gcov enquanto.c
    - name: para
      run:  gcc -ftest-coverage -g3 para.c -o para && ./para && gcov para.c
    - name: nota
      run:  gcc -ftest-coverage -g3 nota.c -o nota && chmod +x nota.sh && ./nota.sh && gcov nota.c
    - name: local
      run:  gcc -ftest-coverage -g3 local.c -o local && bash -x local.sh && gcov local.c
    - name: global
      run:  gcc -ftest-coverage -g3 global.c -o global && ./global && gcov global.c  
    - name: estafeta
      run:  gcc -ftest-coverage -g3 estafeta.c -o estafeta && ./estafeta 5 9 && gcov estafeta.c 
    - name: programar
      run:  gcc -ftest-coverage -g3 programar.c -o programar && ./programar && gcov programar.c
    - name: fibonacci
      run:  bash -x fibonacci.sh
    - name: restante
      run:  bash -x restante.sh 7
    - name: digitos
      run:  bash -x digitos.sh
    - name: baralhar
      run:  bash -x baralhar.sh ATGC && grep -b -o -E 'AT' nucleotideos.txt | wc -l
    - name: Instalação imagemagick e mesclagem de imagens
      run:  sudo apt install -y imagemagick && bash -x imagem.sh 1.jpg 2.jpg
    - name: Verficação de mecla da imagem
      run:  base64 mescla*.jpg
    - name: Instalação sox
      run:  sudo apt install -y sox
    - name: O silêncio é retirado do som
      run:  sox exemplo.wav som.wav silence 1 0.2 1% 1 0.2 1% 
    - name: Comando Bash para retificar o som do ruído de fundo
      run:  sox entrada.wav saida.wav trim 0 0.900
    - name: Gerar um perfil para retificar o som
      run:  sox saida.wav -n noiseprof perfil.prof    
    - name: Limpar o som de ruído
      run:  sox som.wav somlimpo.wav noisered perfil.prof 0.21  
    - name: Gerar nova saída de espectrograma 
      run:  bash -x espectrograma.sh somlimpo.wav somlimpo2.wav
    - name: Verficação de aprendizagem 
      run:  base64 aprender*.png
    - name: Divisão de imagem por canal
      run:  convert -crop 100%x50% aprender*.png saida.png
    - name: Comparação de imagens
      run:  bash -x compararimagem.sh saida-1.png saida-2.png
