name: C
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: random
      run:  apt-get install -y gcovr && gcc -g3 random.c -o random && ./random && gcov random.c || cat random.c
